### ISSUE TITLE
I want to Implement feature where student can add/update their information 

### ISSUE THREAD

**Issue by Ekolinnia** [laurenlastoria/COEN-soen341project2023#7]
Allows the user to upload/update documents such as CV and Cover letters 

This is for user story 3

**Comment by Ekolinnia** [comment]
This is for our student settings page

**Comment by Ekolinnia** [comment]
This is for the profile setting page: Allows the user to upload documents such as CV and Cover letters or add/update their personal information such as their name, field, and contact informations

**Comment by laurenlastoria** [comment]
Students can add resumes and can update their education, location etc.
